# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Metro Explorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Metro Explorer
  pod 'MBProgressHUD', '1.1.0'
  
  target 'Metro ExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Metro ExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
